[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
linea = "${LINEA_RPC_URL}"

[etherscan]
linea = { key = "${LINEASCAN_API_KEY}" }